<!DOCTYPE html>
<html lang="en">
<head>

  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>    
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<!--  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>-->
  <!-- Latest compiled and minified CSS-->
  <!--link(rel='stylesheet', href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')-->
  <!-- Optional theme-->
  <!--link(rel='stylesheet', href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css')-->
  <!-- Latest compiled and minified JavaScript-->
  <!--script(src='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')-->
  <!--css-->
  <!--link(href='http://sites.simbla.com/static/css/bootstrap3.min.css', rel='stylesheet')-->
    <!--<link href="http://static.triballabs.net/Bootstrap/css/bootstrap.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/bootstrap-responsive.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/bootstrap.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/bootstrap-responsive.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/docs.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/tribal-bootstrap.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/tribal-timetable.css" rel="stylesheet"/>
    <!-script(type='text/javascript',src='http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js')-->
    <!--script(type='text/javascript',src='http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js')-->
    <!--script(type='text/javascript',src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js')-->
    
    <!--///////////////////////-->
    <!--script(type='text/javascript', src='http://static.triballabs.net/Bootstrap/js/jquery-latest.js')-->
   <!-- <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/jquery.ba-resize.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/bootstrap-tooltip.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/bootstrap-collapse.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal-shared.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal-timetable.js"></script>
-->
    <!-- Latest compiled and minified CSS-->
    <!--link(rel='stylesheet', href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')-->
    <!-- Optional theme-->
    <!--link(rel='stylesheet', href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css')-->
    <!-- Latest compiled and minified JavaScript-->
    <!--script(src='//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')-->
    <!--script(src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js')-->
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    
    <link href="http://sites.simbla.com/static/css/bootstrap3.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"/>
    <link href="http://sites.simbla.com/static/css/style.css" rel="stylesheet"/>
    <link href="http://sites.simbla.com/static/css/blocks.css" rel="stylesheet"/>
    <!--if IE 7-->
    <link rel="stylesheet" href="http://sites.simbla.com/static/css/font-awesome-ie7.min.css"/>
    <link href="http://sites.simbla.com/static/css/theme-css/wedding.css" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Oxygen:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quicksand:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
   <link rel="stylesheet" type="text/css" media="screen" href="http://tarruda.github.com/bootstrap-datetimepicker/assets/css/bootstrap-datetimepicker.min.css">

  <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap-combined.min.css" rel="stylesheet">

    <script src="http://sites.simbla.com/static/js/jquery.js"></script>
    <meta name="page-source" content="site-id=55c6f14a618ffa7671dd3bd6, page-id=55c6f16a618ffa7671dd3bd7, master-page-id="/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <title>RACOS</title>
    
  </head>

    <body data-offset="80">
    <div id="windowDiv">
      <div id="MarginsTop" style="height: 0px;" class="row"></div>
      <div id="bodyContainer" style="width:100%">
        <div id="P35" data-drag="P35" style="position: relative;" class="simblaEL containerHolder">
          <div style="margin-top: 80px;" class="container">
            <div id="P2" data-drag="P2" class="simblaEL tc">
              <div style="cursor: text;" class="textContainer">
                <h3 style="text-align: center;"><font face="Quicksand" style="font-size: 36px;" color="#f83a22"><b>ROOM INFORMATION</b></font></h3>
              </div>
            </div>
<script type="text/javascript">
 $(function() {
  $('#datepicker').datetimepicker({
    pickTime: false
  });
 });
 $(function() {
  $('#starttimepicker').datetimepicker({
    pickDate: false
  });
 });
 $(function() {
  $('#endtimepicker').datetimepicker({
    pickDate: false
  });
 });

</script>
            <div id="P36" data-drag="P36" class="row simblaEL rDivider">
              <div data-colsize="12" class="sDivider col-md-12 index0">
                <div id="P4" data-drag="P4" class="simblaEL tc"></div>
                <form id="P10" data-drag="P10" action="/schedule/remote/command" method="POST" name="" data-failure="" data-failure-type="text" data-success="" data-success-type="text" class="simblaEL">
                  <div id="P11" data-drag="P11" class="row simblaEL rDivider">
                    <div data-colsize="12" class="sDivider col-md-12 index0">
                      <div id="P22" data-drag="P22" class="simblaEL form-group"> 
                        <label for="P23">ROOM: </label>
                        <input id="P23" type="text" name="room" placeholder="BKD 3201" class="form-control input-lg">
                      </div>
                      <div id="P39" data-drag="P39" class="simblaEL form-group">
                        <label for="P40">ROOM TYPE: </label>
                        <input id="P40" type="text" name="roomtype" placeholder="LECTURE" class="form-control input-lg">
                      </div>
                      <div id="P26" data-drag="P26" class="simblaEL form-group">
                        <label for="P27">COURSE:</label>
                        <input id="P27" name="COURSE" type="text" placeholder="MATH1" class="input-lg form-control">
                      </div>
                      <div id="brands">
                        <label>AC: </label>
                        <select id="remote" name="remote">
                          <option>National</option>
                          <option>Trane</option>
                        </select>
                      </div>
                      <div id="datepicker" data-drag="P24" class="input-append">
                        <label for="P25">DATE:</label>
                        <input id="P25" data-format="yyyy-MM-dd" type="text" name="datepicker" ></input>
                         <span class="add-on">
                           <i data-time-icon="icon-time" data-date-icon="icon-calendar"> </i>
                         </span>
                      </div>
                      <div id="starttimepicker" data-drag="P32" class="input-append">
                        <label for="P33">START TIME:</label>
                        <input id="P33" type="text" name="start_time" data-format="hh:mm:ss"></input>
                          <span class="add-on">
                            <i data-time-icon="icon-time"></i>
                          </span>
                      </div>
                      <div id="endtimepicker" data-drag="P34" class="input-append">
                        <label for="P35">END TIME: </label>
                        <input id="P35" type="text" name="end_time" data-format="hh:mm:ss"></input>
                          <span class="add-on">
                           <i data-time-icon="icon-time"></i>
                          </span>
                      </div>
                      <div id="P42" data-drag="P42" class="simblaEL form-group">
                        <label for="P43">TEMPERATURE (C)</label>
                        <select id="P43" name="temp" class="form-control">
                          <option>16</option>
                          <option>17</option>
                          <option>18</option>
                          <option>19</option>
                          <option>20</option>
                          <option>21</option>
                          <option>22</option>
                          <option>23</option>
                          <option>24</option>
                          <option>25</option>
                          <option>26</option>
                          <option>27</option>
                          <option>28</option>
                          <option>29</option>
                          <option>30</option>
                        </select>
                      </div>
                      <div id="P47" data-drag="P47" class="simblaEL form-group">
                        <label for="P48">FAN LEVEL:</label>
                        <select id="P48" name="fan" class="form-control">
                          <option>1</option>
                          <option>2</option>
                          <option>3</option>
                        </select>
                      </div>
                      <button id="P18" type="submit" data-drag="P18" class="simblaEL btn btn-success btn-lg btn-block">SUBMIT</button>
                    </div>
                  </div>
                  <input type="hidden" name="simblaEmail" value="55c6fab5618ffa7671dd3bdc">
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- .container-->

   <!-- <script src="static/js/bootstrap3.min.js"></script>
    <script src="static/js/simbla.js?v=0.9.1"></script>-->

    <script type="text/javascript"
     src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js">
    </script> 
    <script type="text/javascript"
     src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js">
    </script>
    <script type="text/javascript"
     src="http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.min.js">
    </script>
    <script type="text/javascript"
     src="http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.pt-BR.js">
    </script>
    <script type="text/javascript">
      $('#datetimepicker').datetimepicker({
        format: 'dd/MM/yyyy hh:mm:ss',
        language: 'pt-BR'
      });
    </script>

  </body>
</html>
