<!DOCTYPE html>
<html lang="en">
<head>

  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>    
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <!-- Latest compiled and minified CSS-->
  <!--link(rel='stylesheet', href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')-->
  <!-- Optional theme-->
  <!--link(rel='stylesheet', href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css')-->
  <!-- Latest compiled and minified JavaScript-->
  <!--script(src='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')-->
  <!--css-->
  <!--link(href='http://sites.simbla.com/static/css/bootstrap3.min.css', rel='stylesheet')-->
    <!--<link href="http://static.triballabs.net/Bootstrap/css/bootstrap.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/bootstrap-responsive.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/bootstrap.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/bootstrap-responsive.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/docs.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/tribal-bootstrap.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/tribal-timetable.css" rel="stylesheet"/>
    <!-script(type='text/javascript',src='http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js')-->
    <!--script(type='text/javascript',src='http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js')-->
    <!--script(type='text/javascript',src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js')-->
    
    <!--///////////////////////-->
    <!--script(type='text/javascript', src='http://static.triballabs.net/Bootstrap/js/jquery-latest.js')-->
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/jquery.ba-resize.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/bootstrap-tooltip.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/bootstrap-collapse.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal-shared.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal-timetable.js"></script>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS-->
    <!--link(rel='stylesheet', href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')-->
    <!-- Optional theme-->
    <!--link(rel='stylesheet', href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css')-->
    <!-- Latest compiled and minified JavaScript-->
    <!--script(src='//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')-->
    <!--script(src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js')-->
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://sites.simbla.com/static/css/bootstrap3.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"/>
    <link href="http://sites.simbla.com/static/css/style.css" rel="stylesheet"/>
    <link href="http://sites.simbla.com/static/css/blocks.css" rel="stylesheet"/>
    <!--if IE 7-->
    <link rel="stylesheet" href="http://sites.simbla.com/static/css/font-awesome-ie7.min.css"/>
    <link href="http://sites.simbla.com/static/css/theme-css/wedding.css" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Oxygen:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quicksand:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
    <script src="http://sites.simbla.com/static/js/jquery.js"></script>
    <meta name="page-source" content="site-id=55c6f14a618ffa7671dd3bd6, page-id=55c6f16a618ffa7671dd3bd7, master-page-id="/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <title>RACOS</title>
    
  </head>
  <body data-offset="80">
<div id="windowDiv">
  <div id="MarginsTop" style="height: 0px;" class="row"></div>
  <div id="bodyContainer" style="width:100%">
    <div id="P97" data-drag="P97" style="position: relative;" class="simblaEL containerHolder">
      <div style="margin-top: 80px;" class="container">
        <div id="P98" data-drag="P98" class="row simblaEL rDivider">
          <div data-colsize="12" class="sDivider col-md-12 index0">
            <div id="P73" data-drag="P73" style="position: relative; padding-left: 18px; padding-right: 9px; margin-left: 0px; margin-right: 0px;" class="simblaEL form-group">
              <label for="P74">ROOM: </label>
              <select id="P74" name="room" class="form-control">
                <option></option>
                <option>BKD3201</option>
                <option>BKD3202</option>
                <option>BKD3203</option>
              </select>
            </div>
            <div id="P75" data-drag="P75" style="position: relative; margin-right: 0px; margin-left: 0px;" class="simblaEL form-group">
              <label for="P76">WEEK:</label>
              <select id="P76" name="week" class="form-control">
                <option></option>
                <option>03/08/2015 - 09/08/2015</option>
                <option>03/08/2015 - 09/08/2015</option>
                <option>10/08/2015 - 16/08/2015</option>
                <option>17/08/2015 - 23/08/2015</option>
              </select>
            </div>
          </div>
        </div>
        <div id="P99" data-drag="P99" class="row simblaEL rDivider">
          <div data-colsize="12" class="sDivider col-md-12 index0">
            <div id="P88" data-drag="P88" style="position: relative;" class="simblaEL tc">
              <div style="cursor: text; border-radius: 0px; margin-top: 20px; background-color: rgb(25, 238, 218);" data-border-type="All" class="textContainer">
                <p style="text-align: center;"><b style="font-size: 18px; line-height: 1.428571429;"><font face="Quicksand">Current Room</font><font face="Source Sans Pro"> </font><a href="status" style="font-family: Quicksand;">STATUS</a></b><br/></p>
              </div>
            </div>
          </div>
        </div>
        <div id="P100" data-drag="P100" class="row simblaEL rDivider">
          <div data-colsize="12" class="sDivider col-md-12 index0">
            <div id="P76" data-drag="P76" style="position: relative;" class="simblaEL tc">
              <div style="margin-left: 5px; cursor: text; line-height: 48px;" class="textContainer">
                <p style="text-align: center;"><font style="font-size: 24px;" face="Quicksand" color="#7bd148"><b><a href="/schedule"><b><font face="Quicksand">Existing Schedule</font></b></a></b></font></p>
              </div>
            </div>
            <div id="P93" data-drag="P93" style="position: relative;" class="simblaEL tc">
              <div style="margin-left: 5px; cursor: text; line-height: 48px;" class="textContainer">
                <p style="text-align: center;"><font style="font-size: 24px;" face="Quicksand" color="#7bd148"><b><a href="http://localhost:3000"><b><font face="Quicksand">Add New Schedule</font></b></a></b></font></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

</html>