<!DOCTYPE html>
<html lang="en">
<head>

  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>    
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <!-- Latest compiled and minified CSS-->
  <!--link(rel='stylesheet', href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')-->
  <!-- Optional theme-->
  <!--link(rel='stylesheet', href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css')-->
  <!-- Latest compiled and minified JavaScript-->
  <!--script(src='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')-->
  <!--css-->
  <!--link(href='http://sites.simbla.com/static/css/bootstrap3.min.css', rel='stylesheet')-->
    <!--<link href="http://static.triballabs.net/Bootstrap/css/bootstrap.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/bootstrap-responsive.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/bootstrap.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/bootstrap-responsive.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/docs.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/tribal-bootstrap.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/tribal-timetable.css" rel="stylesheet"/>
    <!-script(type='text/javascript',src='http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js')-->
    <!--script(type='text/javascript',src='http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js')-->
    <!--script(type='text/javascript',src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js')-->
    
    <!--///////////////////////-->
    <!--script(type='text/javascript', src='http://static.triballabs.net/Bootstrap/js/jquery-latest.js')-->
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/jquery.ba-resize.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/bootstrap-tooltip.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/bootstrap-collapse.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal-shared.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal-timetable.js"></script>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS-->
    <!--link(rel='stylesheet', href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')-->
    <!-- Optional theme-->
    <!--link(rel='stylesheet', href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css')-->
    <!-- Latest compiled and minified JavaScript-->
    <!--script(src='//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')-->
    <!--script(src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js')-->
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://sites.simbla.com/static/css/bootstrap3.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"/>
    <link href="http://sites.simbla.com/static/css/style.css" rel="stylesheet"/>
    <link href="http://sites.simbla.com/static/css/blocks.css" rel="stylesheet"/>
    <!--if IE 7-->
    <link rel="stylesheet" href="http://sites.simbla.com/static/css/font-awesome-ie7.min.css"/>
    <link href="http://sites.simbla.com/static/css/theme-css/wedding.css" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Oxygen:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quicksand:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
    <script src="http://sites.simbla.com/static/js/jquery.js"></script>
    <meta name="page-source" content="site-id=55c6f14a618ffa7671dd3bd6, page-id=55c6f16a618ffa7671dd3bd7, master-page-id="/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <title>RACOS</title>
    
  </head>
  
  <body data-offset="80">
    <!--<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" data-toggle="collapse" data-target="#racos-navbar-collapse" class="btn btn-navbar"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a href="/" class="brand">RACOS</a>
          <div id="#racos-navbar-collapse" class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="/schedule">Schedule</a></li>
              <li><a href="/about">About</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>-->


    <div id="windowDiv">
      <div id="MarginsTop" style="height: 0px;" class="row"></div>
      <div id="bodyContainer" style="width:100%">
        <div id="P15" data-drag="P15" style="position: relative; margin-top: 80px;" class="row simblaEL rDivider">
          <div data-colsize="12" class="sDivider col-md-12 index0">
            <div id="P19" data-drag="P19" style="position: relative;" class="simblaEL containerHolder">
              <div style="padding-left: 0px;" class="container">
                <div id="P20" data-drag="P20" style="position: relative;" class="simblaEL tc">
                  <div style="padding-left: 1px; margin-left: 215px; margin-right: 214px; cursor: text; line-height: 60px;" class="textContainer">
                    <h3 style="text-align: center;"><font face="Ubuntu" color="#42d692" style="font-size: 48px;">Welcome to <b>RACOS</b></font></h3>
                    <p style="text-align: center;"><font style="font-size: 14px;">About</font></p>
                  </div>
                </div>
                <div id="P23" data-drag="P23" style="position: relative; padding-left: 226px; padding-right: 6px;" class="simblaEL separatorElm">
                  <div data-type="21" data-color="272a38" style="width: 80%; padding-top: 0.6%; background-image: url(http://sites.simbla.com/static-svg/21/272a38); background-size: auto 100%;"></div>
                </div>
                <div id="P52" data-drag="P52" style="position: relative; margin-top: 30px;" class="row simblaEL rDivider">
                  <div data-colsize="2" class="sDivider col-md-2 index0"></div>
                  <div data-colsize="1" class="sDivider col-md-1 index1">
                    <div id="P38" data-drag="P38" style="" class="simblaEL iconElm"><a href="Exist"><i style="font-size: 30px; text-shadow: none; box-sizing: content-box; line-height: 52px; text-align: center; display: inline-block; overflow: hidden;" data-color="" data-bgcolor="" data-shadow="ns" data-border="circle" class="fa fa-search"></i></a></div>
                  </div>
                  <div data-colsize="9" class="sDivider col-md-9 index2">
                    <div id="P56" data-drag="P56" style="" class="simblaEL tc">
                      <div style="cursor: text;" class="textContainer">
                        <p><font style="font-size: 36px;" face="Oxygen" color="#7bd148"><a href="exist">Existing Room</a></font></p>
                      </div>
                    </div>
                  </div>
                </div>
                <div id="P53" data-drag="P53" style="position: relative;" class="row simblaEL rDivider">
                  <div data-colsize="2" class="sDivider col-md-2 index0"></div>
                  <div data-colsize="1" class="sDivider col-md-1 index1">
                    <div id="P37" data-drag="P37" style="" class="simblaEL iconElm"><a href="Existing"><i style="font-size: 40px; text-shadow: none; box-sizing: content-box; line-height: 45px; text-align: center; display: inline-block; overflow: hidden;" data-color="" data-bgcolor="" data-shadow="ns" data-border="circle" class="fa fa-plus"></i></a></div>
                  </div>
                  <div data-colsize="9" class="sDivider col-md-9 index2">
                    <div id="P57" data-drag="P57" style="" class="simblaEL tc">
                      <div style="cursor: text;" class="textContainer">
                        <p><font style="font-size: 36px;" color="#f83a22" face="Quicksand"><a href="newroom">New Room</a></font></p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- .container-->
      </div>
    </div>
    <script src="http://sites.simbla.com/static/js/bootstrap3.min.js"></script>
    <script src="http://sites.simbla.com/static/js/simbla.js?v=0.9.1"></script>

  </body>

  </html>