<!DOCTYPE html>
<html lang="en">
<head>

  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

  <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/jquery.ba-resize.js"></script>
  <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/bootstrap-tooltip.js"></script>
  <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/bootstrap-collapse.js"></script>
  <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal.js"></script>
  <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal-shared.js"></script>
  <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal-timetable.js"></script>

  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>


  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <link href="http://sites.simbla.com/static/css/bootstrap3.min.css" rel="stylesheet"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"/>
  <link href="http://sites.simbla.com/static/css/style.css" rel="stylesheet"/>
  <link href="http://sites.simbla.com/static/css/blocks.css" rel="stylesheet"/>
    <!--if IE 7-->
    <link rel="stylesheet" href="http://sites.simbla.com/static/css/font-awesome-ie7.min.css"/>
    <link href="http://sites.simbla.com/static/css/theme-css/wedding.css" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Oxygen:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quicksand:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
  <script src="http://sites.simbla.com/static/js/jquery.js"></script>
  <meta name="page-source" content="site-id=55c6f14a618ffa7671dd3bd6, page-id=55c6f16a618ffa7671dd3bd7, master-page-id="/>


  <title>RACOS</title>

</head>
<body ontouchstart="">

  <div id="windowDiv">
    <div id="MarginsTop" style="height: 0px;" class="row"></div>
      <div id="bodyContainer" style="width:100%">
        <div id="P1" data-drag="P1" style="position: relative;" class="simblaEL containerHolder">
          <div style="margin-top: 80px;" class="container">
            <div id="P19" data-drag="P19" class="row simblaEL rDivider">
              <div data-colsize="12" class="sDivider col-md-12 index0">
                <div id="P20" data-drag="P20" class="simblaEL tcH">
                  <div style="cursor: text;" class="textContainer H1">
                    <h1 style="text-align: center;"><font face="Quicksand">ROOM STATUS</font></h1>
                  </div>
                </div>
              </div>
            </div>
            <div id="P2" data-drag="P2" class="row simblaEL rDivider">
              <div data-colsize="6" class="sDivider col-md-6 index0">
                <div id="P21" data-drag="P21" class="simblaEL tcH">
                  <div style="cursor: text;" class="textContainer H1">
                    <h1><font face="Quicksand" style="font-size: 24px;">AC Status</font></h1>
                  </div>
                </div>
                <!--<form id="P5" data-drag="P5" onsubmit="return simblaFormSubmit(this)" method="POST" name="" data-failure="" data-failure-type="link" data-success="" data-success-type="link" action="" class="simblaEL">-->
                  <div id="P35" data-drag="P35" class="simblaEL tc"></div>
                  <div id="P15" data-drag="P15" class="simblaEL tc"></div>
                  <div id="P24" data-drag="P24" class="simblaEL tc">
                    <div style="cursor: text;" class="textContainer">
                      <h3><font style="font-size: 18px;" face="Raleway" color="#444444"><b>ON/OFF:</b></font></h3>
                    </div>
                  </div>
                  <div id="P71" data-drag="P71" style="position: relative; margin-top: -25px;" class="simblaEL form-group">
                    <label for="P72"></label>
                    <input id="P72" type="text" name="powerstatus" placeholder="ON" class="form-control input-lg">
                  </div>
                  <div id="P59" data-drag="P59" class="simblaEL tc">
                    <div style="cursor: text;" class="textContainer">
                      <h3><font style="font-size: 18px;" face="Raleway" color="#444444"><b>Temperature :</b></font></h3>
                    </div>
                  </div>
                  <div id="P31" data-drag="P31" style="position: relative; margin-top: -24px; margin-bottom: 17px;" class="simblaEL form-group">
                    <label for="P32"></label>
                    <input id="P32" type="text" name="name" placeholder="21" class="form-control input-lg">
                  </div>
                  <div id="P36" data-drag="P36" class="simblaEL tc">
                    <div style="cursor: text;" class="textContainer">
                      <h3><font face="Quicksand" color="#444444"><span style="font-size: 18px; line-height: 19.7999992370605px;"><b>Humidity (%):</b></span></font></h3>
                    </div>
                  </div>
                  <div id="P41" data-drag="P41" style="position: relative; margin-top: -25px;" class="simblaEL form-group">
                    <label for="P42"></label>
                    <input id="P42" type="number" name="humid" placeholder="60" class="form-control input-lg">
                  </div>
                <!--</form>-->
              </div>
              <div data-colsize="6" class="sDivider col-md-6 index1">
                <div id="P18" data-drag="P18" class="simblaEL tcH">
                  <div style="cursor: text;" class="textContainer H1">
                    <h1><font face="Quicksand" style="font-size: 24px;">AC Manual Control</font></h1>
                  </div>
                </div>
                <!--<form id="P22" data-drag="P22" onsubmit="" method="POST" name="" data-failure="" data-failure-type="link" data-success="" data-success-type="link" action="" class="simblaEL">
                  <form id="P89" data-drag="P89" onsubmit="" method="POST" name="" data-failure="" data-failure-type="text" data-success="" data-success-type="text" class="simblaEL">
                  -->
                    <div id="P90" data-drag="P90" class="row simblaEL rDivider">
                      <div data-colsize="12" class="sDivider col-md-12 index0">
                        <div id="P66" data-drag="P66" class="simblaEL tc">
                          <!--<div style="cursor: text;" class="textContainer">
                            <h3><font style="font-size: 18px;" face="Raleway" color="#444444"><b>ON/OFF:</b></font></h3>
                          </div>-->
                        </div>
                        <div id="P62" data-drag="P62" style="position: relative; margin-top: -25px;" class="simblaEL form-group">
                        <ul class="remotes" style="list-style-type:none;">
                        {% for remote in remotes %}
                          {% set remoteName = loop.key %}
                          <li class="remote" id="{{ remoteName }}">
                            <ul class="commands" style="list-style-type:none;">
                            {% for command in remote %}
                               <li class="command" style="padding: 5px 0;">
                                 <button class="command-link {% if repeaters[remoteName][command] %}command-repeater{% else %}command-once{% endif %} btn btn-wide btn-large btn-primary" href="/remotes/{{ remoteName }}/{{ command|url_encode }}">{{ labelForCommand(remoteName, command) }}</button>
                               </li>
                               <p> </p>
                               <p> </p>
                            {% endfor %}
                            </ul>
                          </li>
                        {% endfor %}
                        </ul>
                      </div>
                    </div>
                  <!--</form>
                </form>-->
              </div>
      </div>

      <script src="static/js/compiled/app.js" type="text/javascript" charset="utf-8"></script>
</body>
</html>
