<!DOCTYPE html>
<html lang="en">
<head>

  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>    
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <!-- Latest compiled and minified CSS-->
  <!--link(rel='stylesheet', href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')-->
  <!-- Optional theme-->
  <!--link(rel='stylesheet', href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css')-->
  <!-- Latest compiled and minified JavaScript-->
  <!--script(src='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')-->
  <!--css-->
  <!--link(href='http://sites.simbla.com/static/css/bootstrap3.min.css', rel='stylesheet')-->
    <!--<link href="http://static.triballabs.net/Bootstrap/css/bootstrap.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/bootstrap-responsive.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/bootstrap.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/bootstrap-responsive.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/docs.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/tribal-bootstrap.css" rel="stylesheet"/>
    <link href="http://static.triballabs.net/Bootstrap/css/tribal-timetable.css" rel="stylesheet"/>
    <!-script(type='text/javascript',src='http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js')-->
    <!--script(type='text/javascript',src='http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js')-->
    <!--script(type='text/javascript',src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js')-->
    
    <!--///////////////////////-->
    <!--script(type='text/javascript', src='http://static.triballabs.net/Bootstrap/js/jquery-latest.js')-->
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/jquery.ba-resize.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/bootstrap-tooltip.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/bootstrap-collapse.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal-shared.js"></script>
    <script type="text/javascript" src="http://static.triballabs.net/Bootstrap/js/tribal-timetable.js"></script>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS-->
    <!--link(rel='stylesheet', href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')-->
    <!-- Optional theme-->
    <!--link(rel='stylesheet', href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css')-->
    <!-- Latest compiled and minified JavaScript-->
    <!--script(src='//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')-->
    <!--script(src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js')-->
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://sites.simbla.com/static/css/bootstrap3.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"/>
    <link href="http://sites.simbla.com/static/css/style.css" rel="stylesheet"/>
    <link href="http://sites.simbla.com/static/css/blocks.css" rel="stylesheet"/>
    <!--if IE 7-->
    <link rel="stylesheet" href="http://sites.simbla.com/static/css/font-awesome-ie7.min.css"/>
    <link href="http://sites.simbla.com/static/css/theme-css/wedding.css" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Oxygen:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quicksand:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"/>
    <script src="http://sites.simbla.com/static/js/jquery.js"></script>
    <meta name="page-source" content="site-id=55c6f14a618ffa7671dd3bd6, page-id=55c6f16a618ffa7671dd3bd7, master-page-id="/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <title>RACOS</title>
    
  </head>

    <body data-offset="80">



<div id="windowDiv">
  <div id="MarginsTop" style="height: 0px;" class="row"></div>
  <div id="bodyContainer" style="width:100%">
    <div id="P1" data-drag="P1" style="position: relative;" class="simblaEL containerHolder">
      <div style="margin-top: 80px;" class="container">
        <div id="P2" data-drag="P2" class="row simblaEL rDivider">
          <div data-colsize="12" class="sDivider col-md-12 index0">
            <div id="P3" data-drag="P3" class="simblaEL tc">
              <div style="cursor: text;" class="textContainer">
                <h3 style="text-align: center;"><b><font face="Quicksand" style="font-size: 36px;" color="#f83a22">Teach RPi </font></b><br/><br/><br/></h3>
              </div>
            </div>
          </div>
        </div>
        <form id="P73" data-drag="P73" onsubmit="return simblaFormSubmit(this)" method="POST" name="" data-failure="" data-failure-type="text" data-success="" data-success-type="text" style="position: relative; margin-left: 300px; margin-right: 300px; border: 12px solid rgb(142, 199, 172); border-radius: 13px; background-color: rgb(138, 220, 158);" data-border-type="All" class="simblaEL">
          <div id="P74" data-drag="P74" style="position: relative; margin-bottom: 20px;" class="row simblaEL rDivider">
            <div data-colsize="12" class="sDivider col-md-12 index0">
              <div id="P77" data-drag="P77" style="position: relative; margin-top: 20px;" class="simblaEL form-group">
                <label for="P78">New AC Brand</label>
                <input id="P78" type="text" name="newbrand" placeholder="" class="form-control input-lg"/>
              </div>
              <button id="P81" type="submit" data-drag="P81" class="simblaEL btn btn-success btn-lg btn-block">SAVE</button>
            </div>
          </div>
          <input type="hidden" name="simblaEmail" value="55c6fab5618ffa7671dd3bdc"/>
        </form>
        <div id="P14" data-drag="P14" style="position: relative; margin-top: 50px; border: 5px double rgb(142, 199, 172); border-radius: 12px;" data-border-type="All" class="row simblaEL rDivider">
          <div data-colsize="4" class="sDivider col-md-4 index0">
            <form id="P32" data-drag="P32" onsubmit="return simblaFormSubmit(this)" method="POST" name="" data-failure="" data-failure-type="text" data-success="" data-success-type="text" class="simblaEL">
              <div id="P33" data-drag="P33" style="position: relative; margin-top: 30px;" class="row simblaEL rDivider">
                <div data-colsize="12" class="sDivider col-md-12 index0">
                  <button id="P40" type="submit" data-drag="P40" class="simblaEL btn btn-success btn-lg btn-block">POWER</button>
                </div>
              </div>
              <input type="hidden" name="simblaEmail" value="55c6fab5618ffa7671dd3bdc"/>
            </form>
            <form id="P44" data-drag="P44" onsubmit="return simblaFormSubmit(this)" method="POST" name="" data-failure="" data-failure-type="text" data-success="" data-success-type="text" class="simblaEL">
              <div id="P45" data-drag="P45" style="position: relative; margin-top: 30px;" class="row simblaEL rDivider">
                <div data-colsize="12" class="sDivider col-md-12 index0">
                  <div id="P50" data-drag="P50" class="simblaEL form-group">
                    <label for="P51"></label>
                    <select id="P51" name="temp_" class="form-control">
                      <option>16</option>
                      <option>17</option>
                      <option>18</option>
                      <option>19</option>
                      <option>20</option>
                      <option>21</option>
                      <option>22</option>
                      <option>23</option>
                      <option>24</option>
                      <option>25</option>
                      <option>26</option>
                      <option>27</option>
                      <option>28</option>
                      <option>29</option>
                      <option>30</option>
                      <option>16</option>
                      <option>17</option>
                      <option>18</option>
                      <option>19</option>
                      <option>20</option>
                      <option>21</option>
                      <option>22</option>
                      <option>23</option>
                      <option>24</option>
                      <option>25</option>
                      <option>26</option>
                      <option>27</option>
                      <option>28</option>
                      <option>29</option>
                      <option>30</option>
                      <option>16</option>
                      <option>17</option>
                      <option>18</option>
                      <option>19</option>
                      <option>20</option>
                      <option>21</option>
                      <option>22</option>
                      <option>23</option>
                      <option>24</option>
                      <option>25</option>
                      <option>26</option>
                      <option>27</option>
                      <option>28</option>
                      <option>29</option>
                      <option>30</option>
                      <option>16</option>
                      <option>17</option>
                      <option>18</option>
                      <option>19</option>
                      <option>20</option>
                      <option>21</option>
                      <option>22</option>
                      <option>23</option>
                      <option>24</option>
                      <option>25</option>
                      <option>26</option>
                      <option>27</option>
                      <option>28</option>
                      <option>29</option>
                      <option>30</option>
                    </select>
                  </div>
                  <button id="P52" type="submit" data-drag="P52" class="simblaEL btn btn-success btn-lg btn-block">TEMPERATURE</button>
                </div>
              </div>
              <input type="hidden" name="simblaEmail" value="55c6fab5618ffa7671dd3bdc"/>
            </form>
            <form id="P53" data-drag="P53" onsubmit="return simblaFormSubmit(this)" method="POST" name="" data-failure="" data-failure-type="text" data-success="" data-success-type="text" class="simblaEL">
              <div id="P55" data-drag="P55" style="position: relative; margin-top: 30px;" class="row simblaEL rDivider">
                <div data-colsize="12" class="sDivider col-md-12 index0">
                  <div id="P63" data-drag="P63" class="simblaEL form-group">
                    <label for="P64"></label>
                    <select id="P64" name="fan_" class="form-control">
                      <option>1</option>
                      <option>2</option>
                      <option>3</option>
                    </select>
                  </div>
                  <button id="P61" type="submit" data-drag="P61" class="simblaEL btn btn-success btn-lg btn-block">FAN</button>
                </div>
              </div>
              <input type="hidden" name="simblaEmail" value="55c6fab5618ffa7671dd3bdc"/>
            </form>
          </div>
          <div data-colsize="8" class="sDivider col-md-8 index1">
            <form id="P16" data-drag="P16" onsubmit="return simblaFormSubmit(this)" method="POST" name="" data-failure="" data-failure-type="text" data-success="" data-success-type="text" class="simblaEL">
              <div id="P17" data-drag="P17" style="position: relative; margin-top: 80px;" class="row simblaEL rDivider">
                <div data-colsize="12" class="sDivider col-md-12 index0">
                  <div id="P18" data-drag="P18" style="position: relative;" class="simblaEL form-group">
                    <label for="P19">Command</label>
                    <textarea id="P19" name="command" placeholder="" rows="3" class="form-control"></textarea>
                  </div>
                </div>
              </div>
              <div id="P65" data-drag="P65" style="position: relative; margin-top: 0px; margin-left: 0px; padding-left: 205px; padding-right: 216px;" class="row simblaEL rDivider">
                <div data-colsize="12" class="sDivider col-md-12 index0">
                  <button id="P72" type="submit" data-drag="P72" class="simblaEL btn btn-success btn-lg btn-block">END</button>
                </div>
              </div>
            </form>
            <input type="hidden" name="simblaEmail" value="55c6fab5618ffa7671dd3bdc"/><br/><br/><br/>
          </div>
        </div>
      </div>
    </div>
  </div>

<p></p>
<p></p>
  <!-- .container-->
</div>
<script src="http://sites.simbla.com/static/js/bootstrap3.min.js">
  <script src="http://sites.simbla.com/static/js/simbla.js?v=0.9.1"></script>
</script>

</body>
</html>